services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  odoo12:
    build: 12.0/.
    # command: tail -F /dev/null
    environment:
      - OPENUPGRADE_TARGET_VERSION=16.0
      - DATABASE=odoo
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  
  odoo13:
    build: 13.0/.
    # command: tail -F /dev/null
    environment:
      - OPENUPGRADE_TARGET_VERSION=16.0
      - DATABASE=odoo
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  
  odoo14:
    build: 14.0/.
    # command: tail -F /dev/null
    environment:
      - OPENUPGRADE_TARGET_VERSION=16.0
      - DATABASE=odoo
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  odoo15:
    build: 15.0/.
    # command: tail -F /dev/null
    environment:
      - OPENUPGRADE_TARGET_VERSION=16.0
      - DATABASE=odoo
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo

  odoo16:
    build: 16.0/.
    # command: tail -F /dev/null
    environment:
      - OPENUPGRADE_TARGET_VERSION=16.0
      - DATABASE=odoo
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo


volumes:
  pg_data:
